### ISSUE TITLE
Can't install with Composer

### ISSUE THREAD

**Issue by missmatsuko** [fatfishdigital/Navigation#1]
Tried the command from the README:
```
 composer require https://github.com/fatfishdigital/navigation
```

Also tried installing by package name in composer.json:
```
composer require fatfish/navigation
```

Get these errors, respectively:
```
  [UnexpectedValueException]
  Could not parse version constraint //github.com/fatfishdigital/navigation:
  Invalid version string "//github.com/fatfishdigital/navigation"
```
```
[InvalidArgumentException]
  Could not find a matching version of package fatfish/navigation. Check the
  package spelling, your version constraint and that the package is available
   in a stability which matches your minimum-stability (stable).
```

Is this plugin pre-release/not yet listed in Composer? Why it is on the official Craft 3 plugins list already?

**Comment by fatfishdigital** [comment]
@missmatsuko try with composer require https://github.com/fatfishdigital/Navigation.git

its not in the composer package list, so you need to specify git location.

**Comment by fatfishdigital** [comment]
Try it Again with composer package updated to Composer
