### ISSUE TITLE
Issue while creating more than one navigation menu list

### ISSUE THREAD

**Issue by bhashkar007** [fatfishdigital/Navigation#19]
I created more than one navigation menu list. Now problem is that if a menu is common in more than one list, then it renders for last one menu.

For example, I added "Contact" in Header and Footer menu but its showing only for Footer menu. Could you help. I am using custom menu code.

**Comment by fatfishdigital** [comment]
@bhashkar007 Hi bhaskar, Currently  when you create a menu it uses menu name as parameter. since you have two menu with same name it will fetch the last one because last one will be the recently created menu in database. i recommend you to use different menu handle.
