### ISSUE TITLE
Not working on localhost

### ISSUE THREAD

**Issue by maartenheideman** [fatfishdigital/Navigation#20]
Saving, editing off navigations doesn't work on a local environment. The plugin doen't take into account the defined siteUrl for action urls.

If i'll working on a site (with MAMP) running on http://localhost/sitename.com/public/ the action urls are sending to http://localhost/craftnavigation/save and that gives a 404 error.

**Comment by fatfishdigital** [comment]
@maartenheideman Hi, It will be fixed on next release, Please wait for few days

**Comment by fatfishdigital** [comment]
This has now been fixed with the new released.
