### ISSUE TITLE
Settings doesn't work

### ISSUE THREAD

**Issue by rmdiaconu** [fatfishdigital/Navigation#3]
When I go to Settings, this error appears:

craft\web\twig\TemplateLoaderException: Unable to find the template “navigation/settings”. in vendor/craftcms/cms/src/web/twig/TemplateLoader.php:122
Stack trace:
#0 vendor/craftcms/cms/src/web/twig/TemplateLoader.php(75): craft\web\twig\TemplateLoader->_resolveTemplate('navigation/sett...')
#1 vendor/twig/twig/lib/Twig/Environment.php(270): craft\web\twig\TemplateLoader->getCacheKey('navigation/sett...')
#2 vendor/twig/twig/lib/Twig/Environment.php(350): Twig_Environment->getTemplateClass('navigation/sett...')
#3 vendor/craftcms/cms/src/web/twig/Environment.php(40): Twig_Environment->loadTemplate('navigation/sett...', NULL)
#4 vendor/twig/twig/lib/Twig/Environment.php(289): craft\web\twig\Environment->loadTemplate('navigation/sett...')
#5 vendor/craftcms/cms/src/web/View.php(331): Twig_Environment->render('navigation/sett...', Array)
#6 vendor/fatfish/navigation/src/Navigation.php(187): craft\web\View->renderTemplate('navigation/sett...', Array)
#7 vendor/craftcms/cms/src/base/Plugin.php(210): fatfish\navigation\Navigation->settingsHtml()
#8 vendor/craftcms/cms/src/controllers/PluginsController.php(93): craft\base\Plugin->getSettingsResponse()
#9 [internal function]: craft\controllers\PluginsController->actionEditPluginSettings('craftnavigation', Object(fatfish\navigation\Navigation))
#10 vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('edit-plugin-set...', Array)
#13 vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-plugin-set...', Array)
#14 vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('plugins/edit-pl...', Array)
#15 vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('plugins/edit-pl...', Array)
#16 vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#17 vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 web/index.php(21): yii\base\Application->run()
#19 {main}

Version used: Craft CMS 3.0.21

Thank you.

**Comment by fatfishdigital** [comment]
this has been fixed. Currently settings page doesnot have any functionality, Its on still on planning phase.
