### ISSUE TITLE
Arranging navigation items doesn't work

### ISSUE THREAD

**Issue by rmdiaconu** [fatfishdigital/Navigation#4]
In version 1.0.1 of the plugin, arranging items doesn't work.

Version used: Craft CMS 3.0.21

Thank you.

**Comment by fatfishdigital** [comment]
its working fine on my ends, i was not able replicate your issue on my local system.

**Comment by rmdiaconu** [comment]
I see.

I don't know what more details to offer. Still doesn't work on my ends, and I've tried it on several browsers.

**Comment by fatfishdigital** [comment]
Can you explain how are you arranging the links?

If you have a look at the sample below, can you identify anything different to what you are doing?

![issue-0004_navigation-test](https://user-images.githubusercontent.com/37125277/44560673-2dc9d300-a794-11e8-9213-4ed289862449.gif)

**Comment by rmdiaconu** [comment]
FYI, I was arranging the links exactly like in your GIF. But the items didn't move at all. Meanwhile, I've restarted the computer and now it's working.
