### ISSUE TITLE
Can`t open the menu

### ISSUE THREAD

**Issue by ipetrov87** [fatfishdigital/Navigation#5]
Hi! 
I just installed the extension and when I try to open it in Control Panel to create a new menu I got **ParseError** error.

syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
Caused by: ParseError
syntax error, unexpected end of file, expecting function (T_FUNCTION) or const (T_CONST)
in ...\vendor\fatfish\navigation\src\controllers\NavigationController.php at line 200

I am using Craft CMS 3.0.21
OS: Windows 10

**Comment by MDXDave** [comment]
See #7

**Comment by MDXDave** [comment]
The update breaks many things. Better wait the fixes (#7, #8, #9, #10) before updating.

**Comment by ipetrov87** [comment]
ok

**Comment by fatfishdigital** [comment]
This has now been fixed with the new release.
