### ISSUE TITLE
Setting are not described

### ISSUE THREAD

**Issue by ipetrov87** [fatfishdigital/Navigation#6]
I just installed the extension and when go to extension setting it is not clear what they are for 

![capture](https://user-images.githubusercontent.com/14108063/44773466-62b19d80-ab79-11e8-87b7-a0d73947ea5c.PNG)

**Comment by christopherhealey** [comment]
Same issue, is this plugin still being maintained?

**Comment by fatfishdigital** [comment]
This has now been fixed with the new released.
